# Generated by Django 5.1.3 on 2024-12-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
